# Author: Tullie Murrell (tulliemurrell@gmail.com)

# ----------------------------------------------------------------------------------------------
# Machine-local PATH additions (uv, git-lfs, etc.)
# ----------------------------------------------------------------------------------------------

[[ -f "$HOME/.local/bin/env" ]] && source "$HOME/.local/bin/env"

# ----------------------------------------------------------------------------------------------
# Prezto
# ----------------------------------------------------------------------------------------------

if [[ -s "$HOME/.zprezto/init.zsh" ]]; then
  source "$HOME/.zprezto/init.zsh"

  autoload -Uz promptinit
  promptinit
  prompt pure_tullie
fi

# ----------------------------------------------------------------------------------------------
# Aliasas
# ----------------------------------------------------------------------------------------------

# PS
alias psa="ps aux"
alias psg="ps aux | grep "

# Moving around
alias cdb='cd -'
alias cls='clear;ls'

# Show human friendly numbers and colors
alias df='df -h'
alias du='du -h -d 2'

# LS (eza)
alias ls='eza --group-directories-first'
alias ll='eza -la --group-directories-first --git --icons'
alias lt='eza --tree --level=2 --icons'

# Cat (bat)
alias cat='bat --paging=never'

# Common shell functions
alias less='less -r'
alias tf='tail -f'
alias l='less'
alias lh='eza -la --sort=modified --icons | head' # See the last modified files
alias cl='clear'

# Zippin
alias gz='tar -zcvf'

# Kill
alias ka9='killall -9'
alias k9='kill -9'

# Finder
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

# Homebrew
alias brewu='brew update && brew upgrade && brew cleanup && brew prune && brew doctor'

# Override rm -i alias which makes rm prompt for every action
alias rm='nocorrect rm'

# Don't try to glob with zsh so you can do stuff like ga *foo* and correctly 
# have git add the right stuff
alias git='noglob git'

# Global aliases
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g c='| wc -l'
alias -g h='| head'
alias -g l="| less"
alias -g n="| /dev/null"
alias -g s='| sort'
alias -g g='| grep' # now you can do: ls foo g something

# vim
alias vim=nvim

# ----------------------------------------------------------------------------------------------
# Colors
# ----------------------------------------------------------------------------------------------

export GREP_COLOR='1;33'

# ----------------------------------------------------------------------------------------------
# fzf
# ----------------------------------------------------------------------------------------------

export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --preview 'bat --style=numbers --color=always --line-range :500 {}'"

# ----------------------------------------------------------------------------------------------
# Git
# ----------------------------------------------------------------------------------------------

# Makes git auto completion faster favouring for local completions
__git_files () {
    _wanted files expl 'local files' _files
}

# ----------------------------------------------------------------------------------------------
# Key bindings
# ----------------------------------------------------------------------------------------------

bindkey -v                                          # Use vi key bindings
bindkey '^r' history-incremental-search-backward    # [Ctrl-r] - Search backward incrementally for a specified string. The string may begin with ^ to anchor the search to the beginning of the line.

# Emacs style
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# ----------------------------------------------------------------------------------------------
# Last Command
# ----------------------------------------------------------------------------------------------

# Use Ctrl-x,Ctrl-l to get the output of the last command
zmodload -i zsh/parameter
insert-last-command-output() {
LBUFFER+="$(eval $history[$((HISTCMD-1))])"
}
zle -N insert-last-command-output
bindkey "^X^L" insert-last-command-output

# ----------------------------------------------------------------------------------------------
# ZMV
# ----------------------------------------------------------------------------------------------

autoload -U zmv
alias zmv="noglob zmv -W"

# ----------------------------------------------------------------------------------------------
# ZSH functions
# ----------------------------------------------------------------------------------------------

# (f)ind by (n)ame
# usage: fn foo
# to find all files containing 'foo' in the name
function fn() { ls **/*$1* }

# ----------------------------------------------------------------------------------------------
# Vi mode
# ----------------------------------------------------------------------------------------------

set -o vi
export EDITOR=nvim
export VISUAL=nvim

# ----------------------------------------------------------------------------------------------
# Persistent history
# ----------------------------------------------------------------------------------------------
HISTSIZE=10000
SAVEHIST=1000
setopt SHARE_HISTORY

# ----------------------------------------------------------------------------------------------
# Modern CLI tooling
# ----------------------------------------------------------------------------------------------

command -v zoxide  &>/dev/null && eval "$(zoxide init zsh)"
command -v mise    &>/dev/null && eval "$(mise activate zsh)"
command -v direnv  &>/dev/null && eval "$(direnv hook zsh)"
command -v atuin   &>/dev/null && eval "$(atuin init zsh)"

# Starship is installed but not used by default - the prompt is Prezto's
# pure_tullie theme (see above). Swap the `prompt pure_tullie` line above
# for the line below to switch prompts:
#   command -v starship &>/dev/null && eval "$(starship init zsh)"
